### Bach Hoa Nhanh - User Service API Testing
@baseUrl = http://bachhoanhanh/users
@authUrl = http://bachhoanhanh/auth/realms/bachhoanhanh/protocol/openid-connect/token
@clientId = gateway-client

############################################################
# 1. AUTHENTICATION SECTION
############################################################

### Login as ADMIN
# @name adminLogin
POST {{authUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id={{clientId}}&
username=admin&
password=123456

> {%
    client.global.set("admin_token", response.body.access_token);
%}

### Login as STAFF
# @name staffLogin
POST {{authUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id={{clientId}}&
username=teststaff&
password=123456

> {%
    client.global.set("staff_token", response.body.access_token);
%}

### Login as CUSTOMER
# @name customerLogin
POST {{authUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id={{clientId}}&
username=testcustomer&
password=123456

> {%
    client.global.set("customer_token", response.body.access_token);
%}


############################################################
# 2. PUBLIC ENDPOINTS
############################################################

### Register a new Customer (Public)
POST {{baseUrl}}/register
Content-Type: application/json

{
  "phone": "0912345678",
  "lastName": "Nguyen",
  "firstName": "Van B",
  "email": "new_guest@gmail.com",
  "password": "password123"
}


############################################################
# 3. AUTHENTICATED USER ENDPOINTS
############################################################

### Get My Own Profile (Self)
GET {{baseUrl}}/me
Authorization: Bearer {{customer_token}}


############################################################
# 4. ADMIN ONLY ENDPOINTS
############################################################

### Create a new Staff Member
POST {{baseUrl}}/staff
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "hoaian_staff",
  "phone": "0987654321",
  "lastName": "An",
  "firstName": "Hoai",
  "email": "newstaff@bachhoanhanh.vn",
  "password": "password123",
  "dateOfBirth": "1995-06-15",
  "idCardNumber": "012345678901",
  "address": "Ho Chi Minh City",
  "isFemale": false
}

### Get User by Keycloak ID
@targetKeycloakId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

GET {{baseUrl}}/{{targetKeycloakId}}
Authorization: Bearer {{admin_token}}

### Delete User
DELETE {{baseUrl}}/{{targetKeycloakId}}
Authorization: Bearer {{admin_token}}


############################################################
# 5. SECURITY & ROLE VALIDATION
############################################################

### Test STAFF attempting to create staff (Expect 403)
POST {{baseUrl}}/staff
Authorization: Bearer {{staff_token}}
Content-Type: application/json

{
  "username": "hack_staff",
  "phone": "0911111111",
  "lastName": "User",
  "firstName": "Hack",
  "email": "hack_staff@bachhoanhanh.vn",
  "password": "password123",
  "dateOfBirth": "1990-01-01",
  "idCardNumber": "000000000000",
  "isFemale": false
}

### Test CUSTOMER attempting to delete user (Expect 403)
DELETE {{baseUrl}}/{{targetKeycloakId}}
Authorization: Bearer {{customer_token}}