spring.application.name=gateway-service
server.port=9000

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Route 0 - product-service with rate limiter
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args[redis-rate-limiter.replenishRate]=5
spring.cloud.gateway.routes[0].filters[0].args[redis-rate-limiter.burstCapacity]=5
spring.cloud.gateway.routes[0].filters[0].args[redis-rate-limiter.requestedTokens]=1
spring.cloud.gateway.routes[0].filters[0].args[key-resolver]=#{@ipKeyResolver}
# Retry filter on product-service route
spring.cloud.gateway.routes[0].filters[1].name=Retry
spring.cloud.gateway.routes[0].filters[1].args[retries]=3
spring.cloud.gateway.routes[0].filters[1].args[statuses]=BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[0].filters[1].args[backoff.firstBackoff]=3000ms
spring.cloud.gateway.routes[0].filters[1].args[backoff.maxBackoff]=5000ms
spring.cloud.gateway.routes[0].filters[1].args[backoff.factor]=2
spring.cloud.gateway.routes[0].filters[1].args[backoff.basedOnPreviousValue]=false


# Route 1 - order-service
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER:http://localhost:8082/realms/bachhoanhanh}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK:http://localhost:8082/realms/bachhoanhanh/protocol/openid-connect/certs}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Logging
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=DEBUG