name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        shell: powershell
        run: |
          cd bachhoanhanh

          if (Test-Path ".env.prod") {
            Copy-Item .env.prod .env -Force
          }

          docker compose up -d --build --remove-orphans

      - name: Check
        shell: powershell
        run: |
          cd bachhoanhanh
          docker ps