stages:
  - deploy

deploy-all-services:
  stage: deploy
  tags:
    - may cua luong
  script:
    - echo "Dang chuan bi moi truong..."
    - |
      if [ -f .env.prod ]; then
        cp .env.prod .env
        echo "Da ap dung cau hinh tu .env.prod"
      else
        echo "Khong tim thay .env.prod, su dung cau hinh mac dinh."
      fi
    - echo "Bat dau Build va Deploy toan bo Microservices..."
    - docker-compose up -d --build --remove-orphans
    - echo "Kiem tra trang thai cac service:"
    - docker ps
  environment:
    name: development