server {
    listen 80;
    server_name bachhoanhanh;

    location / {
        proxy_pass http://gateway-service:9000;
    }

    location /auth/ {
        rewrite ^/auth/(.*)$ /$1 break;

        proxy_pass http://host.docker.internal:8082/;

        proxy_set_header Host localhost:8082;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}