spring.datasource.url=jdbc:mariadb://mariadb:3306/appdb
spring.datasource.username=appuser
spring.datasource.password=apppassword

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka