spring.application.name=product-service
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/productdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# =============REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Enable Spring Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# =============AWS S3 PRODUCT MEDIA
app.media.s3.bucket=${AWS_S3_BUCKET:bachhoanhanh-media}
app.media.s3.region=${AWS_REGION:ap-southeast-1}
app.media.s3.public-base-url=${AWS_S3_PUBLIC_BASE_URL:}
